### ISSUE TITLE
Issue getting screenshots and 3d model

### ISSUE THREAD

**Issue by zoroxd** [csgofloat/CSGOFloat-Inspect#64] opened 2020-06-18 02:42 UTC
![image](https://user-images.githubusercontent.com/67084802/84971845-3f375880-b13b-11ea-8249-1cb252b10634.png)
![image](https://user-images.githubusercontent.com/67084802/84971950-7a398c00-b13b-11ea-9589-6f07a24bdada.png)

**Comment by Step7750** [comment] 2020-06-18 02:43
Duplicate of #58

**Closed by Step7750** 2020-06-18 02:43 UTC
